### ISSUE TITLE
Two way communication

### ISSUE THREAD

**Issue by herrjemand** [phimage/CallbackURLKit#12]
How would you implement two way communication described in http://x-callback-url.com/examples/

Something like: 
> targetapp://x-callback-url/translate?
   x-success=sourceapp://x-callback-url/acceptTranslation&
   x-source=SourceApp&
   x-error=sourceapp://x-callback-url/translationError&
   word=Hello&
   language=Spanish

**Comment by phimage** [comment]
Using closure on one side to receive response
https://github.com/phimage/CallbackURLKit#use-callback-closure

And on the other side by calling success(with param or not) or failure(with error) or cancel
https://github.com/phimage/CallbackURLKit#add-new-action

**Comment by herrjemand** [comment]
@phimage so do I need to declare a new manager instance in my client class to handle incoming callbacks?

**Comment by phimage** [comment]
one manager by app, you can use the default one

**Comment by herrjemand** [comment]
@phimage ok, I don't exactly understand closures with on* operations

I have Client class:

```swift
            try self.perform(action: "runOperation", parameters: parameters,  onSuccess: { parameters in
                
            }, onFailure: nil, onCancel: nil)
```

How do I pass sourceapp://x-callback-url/acceptTranslation on x-success?

**Comment by phimage** [comment]
did you need to know how to do it exactly or just fulfil a need to interact with two of your applications?
Maybe one is not yours and need specific this url

The framework do it automatically but use sourceapp://x-callback-url/response/ for error or success and pass an ID to retrieve the code to execute in callback

**Comment by herrjemand** [comment]
@phimage https://github.com/phimage/CallbackURLKit/blob/master/Sources/Manager.swift#L197
that implies that callback will happen to /response?

**Comment by phimage** [comment]
Yes this is the code
This is an auto communication

We could add an 'Action'(string) by callback type and change here the URL if this action is specified

**Comment by herrjemand** [comment]
@phimage hm.. Can't I just set it as one of the params? 

```
let parameters = [
    "x-succes": "sourceapp://x-callback-url/acceptTranslation"
]
```

**Comment by herrjemand** [comment]
@phimage additionally I am adding this plugin to the ObjectiveC app, and app delegate is actually in obj-c, and I can figure out how to add Manager.shared to pass it url handling

**Comment by phimage** [comment]
yes you can try to put this as parameters, never tried... I expect that I do not filter it

for obj-c I never tried if there is some incompatibility
You cannot access `register` ?
```
CallbackURLKit.register(action: "acceptTranslation") { parameters, _, _, _ in

}
```

**Comment by herrjemand** [comment]
@phimage Setting as parameter works. 

I am working on Objective-c event binding to swift. I found this is how they do it in https://github.com/aerogear/aerogear-cordova-oauth2/

Here they are catching call https://github.com/aerogear/aerogear-cordova-oauth2/blob/master/src/ios/AppDelegate%2Burl.m#L36 which calls notification event

and here is the handler for event https://github.com/aerogear/aerogear-cordova-oauth2/blob/master/src/ios/oauth-0.4.0/OAuth2Module.swift#L92

**Comment by phimage** [comment]
with swizzle they try to achieve this automatically but it's not mandatory
https://github.com/phimage/CallbackURLKit#handle-incoming-urls
