### ISSUE TITLE
macOS 10.13 Issue

### ISSUE THREAD

**Issue by Radagan** [phimage/CallbackURLKit#13]
I'm using your framework in a project running on the 10.13 beta and while it sends x-callbacks without a problem to an installed app (Ulysses, a writing program that has great x-callback support), I don't receive the callback. It's like my registration is ignored. 

There's not much code...

The Ulysses App Client:

```
import Cocoa
import os.log
import CallbackURLKit

public class UlyssesClient: Client {
    
    var ulyssesAuthSuccess = ""
    var ulyssesAuthError = ""
    var ulyssesScheme = "ulysses"
    
    init() {
        super.init(urlScheme:"ulysses")
        ulyssesAuthSuccess = "fictivity://x-callback-url/auth-success"//.addingPercentEncoding(withAllowedCharacters: .urlHostAllowed)!
        ulyssesAuthError = "fictivity://x-callback-url/auth-error"//.addingPercentEncoding(withAllowedCharacters: .urlHostAllowed)!
        //os_log("%@", ulyssesURLString)
        
        CallbackURLKit.register(action: "auth-success") { parameters, success, failure, cancel in
            os_log("auth-success")
            for parameter in parameters {
                os_log("%@ = %@", parameter.key, parameter.value)
            }
        }
        
        CallbackURLKit.register(action: "auth-error") { parameters, success, failure, cancel in
            os_log("auth-error")
            for parameter in parameters {
                os_log("%@ = %@", parameter.key, parameter.value)
            }
        }
    }
    
    func authorize(onSuccess: SuccessCallback? = nil, onFailure: FailureCallback? = nil, onCancel: CancelCallback? = nil) throws {
        try self.perform(action: "authorize", parameters: ["appname": "Fictivity", "x-success": ulyssesAuthSuccess, "x-error": ulyssesAuthError], onSuccess: onSuccess, onFailure: onFailure, onCancel: onCancel)
    }
}
```

In AppDelegate:

```
func applicationDidFinishLaunching(_ aNotification: Notification) {
         let manager =  Manager.shared
        manager.callbackURLScheme = Manager.urlSchemes?.first
        Manager.shared.registerToURLEvent()
    }
```

I did try changing the url scheme name, and confirmed that Ulysses give an error that there isn't any support for that url scheme. So, Ulysses is replying, the reply is just not propagating.

Any ideas?

**Comment by phimage** [comment]
Before I test myself when I have time did you try on Sierra? so this is a real macOS 10.13 Issue

**Comment by phimage** [comment]
I made a client class
https://github.com/phimage/CallbackURLKit/blob/master/Clients/Ulysses.swift
I tested it in demo app
https://github.com/phimage/CallbackURLKit/blob/master/SampleApp/CallbackURLKitDemo/ViewController.swift

**Comment by Radagan** [comment]
Thank you! Your excellent example code popped the error immediately: .callbackURLSchemeNotDefined. The main storyboard's Application did not have the AppDelegate attached, so the registration was not getting called. 

Please forgive my hasty code prior. I came to your library after failing to get urls directly testing 10.13. But it's such a nice library that I think I'll use it. Would you like a pull request when I finish the full client for Ulysses? 

Either way, thank you for your time and effort.

**Comment by phimage** [comment]
@Radagan yes a pull request is welcome. I will add you to credit.

Ulysses is good example, well documented
