### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by andreasluca** [phimage/CallbackURLKit#16]
Are you planning to release a new official version?

**Comment by phimage** [comment]
Since 2.0.0 commit, there is commit that you need? Or did you have an issue with current release?

Please show me the needed commit hash
And I can make a release with release note about it

**Comment by andreasluca** [comment]
I was looking at the releases (https://github.com/phimage/CallbackURLKit/releases) and wanted to download the latest stable that supports swift 4 and the latest Xcode 9. 
I've seen that the master branch is supporting Swift 4 and the latest Xcode, just wondered if there is an official release of it. I can't use cocapods because of my environment, so that's why I was looking for an official release.

Thank you!

**Comment by phimage** [comment]
There is no description for the release
but 2.0.0 (the tag) is swift4 compatible

and if you use cocoapod
[![Cocoapod](http://img.shields.io/cocoapods/v/CallbackURLKit.svg?style=flat)](http://cocoadocs.org/docsets/CallbackURLKit/)

**Comment by phimage** [comment]
I have created the release in github
