### ISSUE TITLE
Unable to install CallbackURLKit via CocoaPods

### ISSUE THREAD

**Issue by andreasluca** [phimage/CallbackURLKit#19]
Hello,

I've tried to run the Demo App but after running: "pod install" I get the following error:

`andreasluca:SampleApp lucaandr$ pod install
Analyzing dependencies
Fetching podspec for `CallbackURLKit` from `../CallbackURLKit.podspec`
[!] CocoaPods could not find compatible versions for pod "CallbackURLKit/GoogleChrome":
  In Podfile:
    CallbackURLKit/GoogleChrome (from `../CallbackURLKit.podspec`)

Specs satisfying the `CallbackURLKit/GoogleChrome (from `../CallbackURLKit.podspec`)` dependency were found, but they required a higher minimum deployment target.`

Do you know why is that?

Thank you

**Comment by phimage** [comment]
could you try to edit the Podfile
and set
  platform :osx, '10.11'
instead of 
  platform :osx, '10.10'

or update the project because I commit it

**Comment by andreasluca** [comment]
I did it installs the pods but it shows some warnings... 
Thank you tho!

There are some other small issues: 
- If you want to launch the SampleApp it won't show the main storyboard, you need to add "var window: UIWindow?" in the AppDelegate.
- If you click the "Print message" the bug prints a message in the Xcode console but it remains in a buggy/frozen state.

Do you want me to report them in an other issue or it's ok to leave them here?

Thank you!

**Comment by phimage** [comment]
I add a DispatchQueue (main by default) to send response to a x-callback-url call

**Comment by andreasluca** [comment]
I will check it up in some hours, thanks.
Btw: if I open just the SampleApp project, embed a compiled CallbackURLKit.framework, remove the cocoapods scripts and I add all the missing files to the project (GoogleChrome, Client, Request, Manager...) I get this errors:
- "Ambiguous use of 'error(code:failureReason:)'"
- URL is not recognized in the GoogleChrome.swift file
(If I comment the lines that produce the errors the app can be executed tho)

Do you know why? Or can we fix this?

**Comment by phimage** [comment]
need the line of code for the error to understand

**Comment by andreasluca** [comment]
So you need to add the SourceFiles and the Client files to the Demo, build a CallbackURLKit framework and embed it to the Demo and then remove all the Pod dependencies, so when you build it you will end up with something like this:

https://imgur.com/a/4V8JRxN

**Comment by phimage** [comment]
If you have the framework compiled and the source
You have two times the code
So that's the definition of ambiguous, xcode compiler do not known which code you want to use

**Comment by andreasluca** [comment]
I updated the link of the images

**Comment by phimage** [comment]
ok for the URL
I have added import Foundation in google (Ulysses.swift have already it)
some project need that

**Comment by andreasluca** [comment]
Yes with the Foundation import it works. And what about the other ambiguous errors, do you know why they appear?

**Comment by phimage** [comment]
As I say I do not understand why you have the code(swift code) and the framework compiled
You have two times the code so there is ambiguity

**Comment by andreasluca** [comment]
True, you are right, I was rushing it and added them because if you don't added them it can't find the Framework utilities:
https://ibb.co/c9mTnp
