### ISSUE TITLE
response path should be prefixed with "/" when building callback URLs

### ISSUE THREAD

**Issue by cpatterson-lilly** [phimage/CallbackURLKit#2]
The x-success, x-failure and x-cancel callback URLs are not being constructed correctly; they are always empty strings. Thus, callbacks do not function properly.

In Manager.swift, line 199, it should be changed from:

    xcuComponents.path = kResponse

to:

    xcuComponents.path = "/" + kResponse

See the [documentation](https://developer.apple.com/library/ios/documentation/Foundation/Reference/NSURLComponents_class/#//apple_ref/occ/instp/NSURLComponents/URL) for the NSURLComponents.URL property:

> If the components object has an authority component (user, password, host, or port) and a path component, then the path must either begin with "/" or be an empty string. Otherwise, this property contains nil.

**Comment by phimage** [comment]
thanks
don't hesitate to PR next time
