### ISSUE TITLE
client.perform() never reaches onSuccess

### ISSUE THREAD

**Issue by kimaldis** [phimage/CallbackURLKit#20]
I've successfully managed to send an action to Bear (MacOS, note taking app) using the code below that appends text to a note but I'm struggling with return parameters. I should be getting not contents back but onSuccess never gets called. Any thoughts on what I may be missing?

		let manager =  Manager.shared
		manager.callbackURLScheme = "bear"

		let client = Client(urlScheme: "bear")

		do {
			try client.perform(
						action: "add-text",
						parameters: ["title": "BearNote", "text" : "some text", "mode" : "append" ],
						onSuccess: { parameters in  
                                                       // never gets here
							print( "Succeed" )
						},
						onFailure: { error in
							print( "Fail" )
						},
						onCancel: {
							print( "Cancelled" )
						}
				)
		} catch {
			print( "Error: \(error)" )
		}

**Comment by phimage** [comment]
You must defined an url scheme for your app
https://github.com/phimage/CallbackURLKit#add-x-callback-url-support-to-your-app
```swift
let manager =  Manager.shared
manager.callbackURLScheme = "YOURappscheme"
```

why? because bear app will call your app using this scheme and onSuccess or onFailure or onCancel  will be called

**Comment by kimaldis** [comment]
Got it. That worked except I'm now I get an error;

      There is no application set to open the URL bearbar://x-callback-url/response?responseType=success&requestID=C09153F6-CA5F-4EA5-9781-935FB70AC168&title=BearNote&note=%23%20BearNote%0Asome%20text%0Asome%20text%0Asome%20text%0Asome%20text%0Asome%20text%0Asome%20text%0Asome%20text%0Asome%20text%0Asome%20text%0Asome%20text%0Asome%20text%0Asome%20text%0Asome%20text&.

**Comment by phimage** [comment]
So your scheme is bearbar?

you must add this scheme on your project , see readme

**Comment by kimaldis** [comment]
isn't that what this does?

    let manager =  Manager.shared
    manager.callbackURLScheme = "bearbar"

**Comment by phimage** [comment]
I already put a link in my first comment
https://github.com/phimage/CallbackURLKit#register-your-url-scheme

**Comment by phimage** [comment]
I am talking about the image
![image](https://user-images.githubusercontent.com/8875768/45633175-68771080-ba9f-11e8-8cb7-080984677078.png)

this edit your info plist

**Comment by kimaldis** [comment]
Got it working.

Thanks for your patience.

**Comment by phimage** [comment]
You are welcome

Please close
