### ISSUE TITLE
Update Demo App

### ISSUE THREAD

**Issue by andreasluca** [phimage/CallbackURLKit#21]
Hello,

As a proposal, I'd suggest the following:
- Updating the Demo App to Swift 4.2 
- Resolving the warnings that appear in Xcode 10
- To me it does not make a lot of sense the Demo App to have Pod dependencies when all the files are already in the repo. Wouldn't it be better to have the App compiling the local sources instead of having a pod dependency?

Thanks (it's just a suggestion)!

**Comment by phimage** [comment]
Hello,
thanks for the suggestions
Do not hesitate to Pull Request if you have converted the demo app

For the demo app, podfile with " :path =>" is used for this purpose ie. development pod
