### ISSUE TITLE
Ampersands in callback URL query strings should be percent-encoded.

### ISSUE THREAD

**Issue by cpatterson-lilly** [phimage/CallbackURLKit#3]
In Manager.swift, in the `Manager.sendRequest(_:)` method, the `x-success`, `x-failure` and `x-cancel` parameters to the outgoing URL include their own query strings that include `responseType` and `requestID` parameters as well as any response parameters for a given action. 

The ampersand characters (&) that delimit these embedded query strings should be percent-encoded; otherwise, they get parsed as query parameters of the outgoing URL, instead of the response URLs.

A typical URL that is built by this method looks like this, just before calling `Manager.openURL(URL)` (in line 228):

```
otherapp://x-callback-url/actionName?x-source=MyAppName&
  x-error=myapp://x-callback-url/response?responseType=error&requestID=9CE4D406-EB4E-4242-8ACD-14851A81A588&
  x-cancel=myapp://x-callback-url/response?responseType=cancel&requestID=9CE4D406-EB4E-4242-8ACD-14851A81A588&
  x-success=myapp://x-callback-url/response?responseType=success&requestID=9CE4D406-EB4E-4242-8ACD-14851A81A588
```

The problem is that the `requestID` parameter gets stripped from the response URLs, thus the `Manager.handleOpenURL(_:)` method fails to match up the response to its request (on line 77) and does not call the response handler closures.

**Comment by phimage** [comment]
I will add something like that on String to do the job

 ```swift
    var urlQueryEncoded: String? {
        return self.stringByAddingPercentEncodingWithAllowedCharacters(NSCharacterSet.URLQueryAllowedCharacterSet())
    }
```

**Comment by cpatterson-lilly** [comment]
That won't work, because the ampersand character is in the URLQueryAllowedCharacterSet.

You'll need to do something like:

```swift
var ampersandEncoded: String? {
    let nonAmpersandCharacters = NSCharacterSet(charactersInString:"&").invertedSet
    return self.stringByAddingPercentEncodingWithAllowedCharacters(nonAmpersandCharacters)
}
```

...then apply that to each of the callback URL query strings.

**Comment by phimage** [comment]
ok I misunderstood the problem and copy wrong code from another project.

when I have access to a mac computer and xcode I will fix this

**Comment by phimage** [comment]
fixed by encoding the query parameters with:
```swift
    var queryEncodeRFC3986: String {
        let generalDelimitersToEncode = ":#[]@" // does not include "?" or "/" due to RFC 3986 - Section 3.4
        let subDelimitersToEncode = "!$&'()*+,;="
        
        let allowedCharacterSet = NSCharacterSet.URLQueryAllowedCharacterSet().mutableCopy() as! NSMutableCharacterSet
        allowedCharacterSet.removeCharactersInString(generalDelimitersToEncode + subDelimitersToEncode)
        
        return self.stringByAddingPercentEncodingWithAllowedCharacters(allowedCharacterSet) ?? self
    }
```
and don't let `NSURLComponents` encode again (or incorrectly) the query by using `percentEncodedQuery`property
