### ISSUE TITLE
Explicit handlers for success and error callbacks

### ISSUE THREAD

**Issue by dshomoye** [phimage/CallbackURLKit#30]
This is not so much of a problem, but more of a question (not sure where else to ask).
It's my first time writing swift and working with xcode so apologies if this looks trivial:

Here's my set up:
I have added a URL type to my app:

<img width="917" alt="image" src="https://user-images.githubusercontent.com/5133948/110217792-e9424680-7e6a-11eb-9146-d15fa0535697.png">

I created a custom client for the Bear app: 
```swift
class BearClient: Client {
    init() {
        super.init(urlScheme: "bear")
    }
    public func search(query: String) {
        let parameters = ["term": query]
        do {
            try self.perform(
                action: "search",
                parameters: parameters,
                onSuccess: { parameters in
                    print(parameters?["notes"])
                },
                onFailure: {error in
                    print(error)
                },
                onCancel: {
                    print("cancelled")
                }
            )
        } catch {
//            NOOP
        }
    }
}
```

I have the manager initialized:
```swift
import SwiftUI
import CallbackURLKit

let manager = Manager.shared

@main
struct LookBackApp: App {
    
    init() {
        manager.callbackURLScheme = "lookback"
    }
    
    var body: some Scene {
        WindowGroup {
            ContentView()
                .onOpenURL(perform: { url in
                   _ = manager.handleOpen(url: url)
                })
        }
    }
}

```
When I call the client like so:

```swift
        let client = BearClient()
        client.search(query: "the")
```

the client runs (and the Bear app opens with the right search query) but the `onSuccess` callback is never called. 

What am I missing? I was assuming I don't create any specific handlers for success and error on the manager because that is not documented.

**Comment by dshomoye** [comment]
Okay so I just noticed that the callback does seem to be working - but each `onSuccess` callback is spinning up a separate window. The actual callback that's passed doesn't get triggered, but specifying a callback will make the app receive the results in a new instance that macOs spins up. I'm guessing this is probably because iOS doesn't have to worry about windows. If I could figure out a way to get SwiftUI to always redirect to the current window then I think this could be resolved.

**Comment by phimage** [comment]
the callback are called only if the app respond to it, this an optional part of the protocol

for that an action must be implemented like described
https://github.com/phimage/CallbackURLKit#add-new-action
`success, failure, cancel` are closure to call to respond

there is an example here 
https://github.com/phimage/CallbackURLKit/blob/master/SampleApp/CallbackURLKitDemo/CallbackURLKitDemo.swift#L43

**Comment by dshomoye** [comment]
Thanks for replying! I haven't gotten around to testing this but I don't really need the app anymore, for now. 
Don't want to keep issues cluttered so I'll close this.
